# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 211fbecd25464fd2b22b86b890c9a0bca29cffe0f3999576553c1df483fef2ee8ae561569150f1b524e31d0e421720a4f2115c45b8579c91a1f10a4885b4916d

test:
  secret_key_base: 0ef0e9574ea0a11004a42d934732d5b81497c1bbc93593a3125606053dafc8ae99eb1b6ab2bf02704e08f5922dfafaeba03248f4927c1f7457def23c37cd7b85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
